backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'features' # Used in routes, e.g., /admin/collections/blog
    label: 'Features' # Used in the UI
    label_singular: 'feature'
    folder: '/content/features' # The path to the folder where the documents are stored
    description: 'Features'
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'feature',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - { label: 'Description', name: 'description', widget: 'string' }
  - name: 'entrenadores' # Used in routes, e.g., /admin/collections/blog
    label: 'Entrenadoes' # Used in the UI
    label_singular: 'entrenador'
    folder: '/content/entrenadores' # The path to the folder where the documents are stored
    description: 'entrenadores'
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'feature',
        }
      - { label: 'Nombre', name: 'nombre', widget: 'string' }
      - {
          label: 'Responsabilidad',
          name: 'responsabilidades',
          widget: 'string',
        }
      - {
          label: "Licencias (dividir con ',')",
          name: 'licencias',
          widget: 'string',
        }
      - { label: 'Descripcion', name: 'descripcion', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'paginas' # Used in routes, e.g., /admin/collections/blog
    label: 'paginas' # Used in the UI
    label_singular: 'pagina'
    folder: '/content/paginas' # The path to the folder where the documents are stored
    description: 'Paginas de informacion'
    create: true # Allow users to create new documents in this collection
    slug: '{{pagina}}-{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Nombre', name: 'nombre', widget: 'string', required: false }
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'feature',
        }
      - {
          label: 'Pagina',
          name: 'pagina',
          widget: 'select',
          options:
            [
              'infoGeneral',
              'natacion',
              'carrera',
              'entrenadores',
              'foro',
              'requisitos',
              'precios',
              'ventajas',
              'federarse',
            ],
        }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
